# Generated by Django 3.1.3 on 2020-11-30 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDiversityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=128)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('diversity_categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=128)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Naics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('standard_employee_count', models.IntegerField(blank=True, null=True)),
                ('standard_revenue', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
